spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: codegendb
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration